### ISSUE TITLE
Abstract should be empty if not available at dataset level

### ISSUE THREAD

**Issue by p1d1d1** [davidoesch/geoservice_harvester_poc#27]
@davidoesch For some layers you're storing in the field "ABSTRACT" the text coming from the service abstract (I assume you do it when abstract at dataset level is missing).
Could you please fix this? 
Abstract at dataset level is missing/empty --> Field "ABSTRACT" is empty

**Comment by davidoesch** [comment]
can you give me an example service and dataset?

**Comment by p1d1d1** [comment]
You are actually concatenating Abstract from service, Abstract from layer and AccessConstraints from service:

https://wms.geo.sh.ch/wms?service=WMS&request=GetCapabilities&version=1.3.0

layer name: sh.landwirtschaft.reben.rebbaukataster

**Comment by davidoesch** [comment]
IMHO closed with https://github.com/davidoesch/geoservice_harvester_poc/commit/a63266f06949b5d4df51f542a41ec2772f45f5ea
