### ISSUE TITLE
Keywords should not be concatenated

### ISSUE THREAD

**Issue by p1d1d1** [davidoesch/geoservice_harvester_poc#29]
@davidoesch  As far as I can see for the field "KEYWORDS" you are concatenating keywords at service level with keywords at dataset level.
This should be avoided. Could you please fix it?

**Comment by davidoesch** [comment]
give a a servie and dataset example

**Comment by p1d1d1** [comment]
e.g. 
https://wms.geo.sh.ch/wms?service=WMS&request=GetCapabilities&version=1.3.0

layer name: sh.landwirtschaft.reben.rebbaukataster
