### ISSUE TITLE
GROUP

### ISSUE THREAD

**Issue by p1d1d1** [davidoesch/geoservice_harvester_poc#30]
@davidoesch so far for the attribute "GROUP" you're setting the closest parent of a layer. Would it be possible to set this to empty is the closest parent is the root of the entire hierarchy?

**Comment by davidoesch** [comment]
and example service and dataset?

**Comment by p1d1d1** [comment]
wms.geo.admin.ch
layer ch.are.reisezeit-agglomerationen-oev should have GROUP empty

**Comment by p1d1d1** [comment]
@davidoesch you can skip this for now, since it could be an issue for WMS which only provide one dataset
